// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type School struct {
	ID        string
	Name      string
	Register  string
	Unit      string
	Address   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
